# Fallback quiz database for 8 modules - English Version

QUIZ_FALLBACKS = {
    1: [ # Phishing Basics
        {"question": "What is phishing?", "options": ["A. Catching fish at sea", "B. Data theft through fake links/messages", "C. Deleting viruses", "D. Fixing computers"], "correct_answer_index": 1, "explanation": "Phishing comes from 'fishing', meaning baiting victims to give personal data."},
        {"question": "Which of these is a characteristic of a phishing email?", "options": ["A. Official sender address", "B. No links included", "C. Urgent or threatening request", "D. Using your real name"], "correct_answer_index": 2, "explanation": "Scammers often create panic so you click quickly without thinking."},
        {"question": "What is the function of HTTPS (green padlock)?", "options": ["A. Indicates the site is 100% safe", "B. Encrypts data between you and the server", "C. Deletes phone viruses", "D. Speeds up internet"], "correct_answer_index": 1, "explanation": "HTTPS protects data during transmission, but phishing sites can also use it."},
        {"question": "What is meant by 'Social Engineering'?", "options": ["A. Technique of manipulating people's psychology", "B. Studying social science", "C. Fixing machines", "D. Creating social media accounts"], "correct_answer_index": 0, "explanation": "Scammers trick your mind, not just the computer system."},
        {"question": "Never give your OTP code to...", "options": ["A. Friends", "B. Bank staff", "C. Anyone", "D. Family"], "correct_answer_index": 2, "explanation": "OTP is your final secret key; banks never ask for it."},
        {"question": "If you see the link 'cimb-niaga.xyz', is it official?", "options": ["A. Yes", "B. Maybe", "C. No, official banks use local domains like .co.id", "D. Yes, because it has the bank name"], "correct_answer_index": 2, "explanation": "Scammers often use cheap domains like .xyz, .tk, or .ml."},
        {"question": "Why do scammers use real bank logos?", "options": ["A. To look cool", "B. To appear trustworthy", "C. Pure coincidence", "D. Bank orders"], "correct_answer_index": 1, "explanation": "Visuals that look real make it easier for scammers to trap victims."},
        {"question": "What should you do if your account is hacked?", "options": ["A. Cry", "B. Change password and contact the bank immediately", "C. Do nothing", "D. Delete the app"], "correct_answer_index": 1, "explanation": "A quick response can minimize financial losses."},
        {"question": "Who is the main target of phishing?", "options": ["A. Only wealthy people", "B. Only non-tech users", "C. Anyone with a digital account", "D. Young people"], "correct_answer_index": 2, "explanation": "Anyone can be a target, which is why literacy is important."},
        {"question": "What service does OctoSight provide?", "options": ["A. Online loans", "B. Security verification for links/messages", "C. Selling mobile credit", "D. Photo editing"], "correct_answer_index": 1, "explanation": "OctoSight helps you distinguish digital threats."}
    ],
    2: [ # Phishing Prevention
        {"question": "What is the best way to avoid phishing?", "options": ["A. Do not use the internet", "B. Always manually check the URL address", "C. Trust all messages", "D. Use expensive antivirus"], "correct_answer_index": 1, "explanation": "Carefully checking the URL is the most effective first line of defense."},
        {"question": "The purpose of 2-Factor Authentication (2FA) is...", "options": ["A. Increase login speed", "B. Second security layer after password", "C. To make account look cool", "D. To replace password function"], "correct_answer_index": 1, "explanation": "Even if the password is stolen, scammers still need the second code (SMS/App)."},
        {"question": "What is 'Hovering' over a link?", "options": ["A. Clicking the link", "B. Hovering cursor without clicking to see real URL", "C. Deleting the link", "D. Sharing the link"], "correct_answer_index": 1, "explanation": "Link text can be deceptive, but the browser status bar shows its true destination."},
        {"question": "A strong password consists of...", "options": ["A. Date of birth", "B. Child's name", "C. Mix of letters, numbers, and symbols", "D. 123456"], "correct_answer_index": 2, "explanation": "Complex combinations are hard for hacking machines to guess."},
        {"question": "Is it safe to store passwords in unencrypted phone notes?", "options": ["A. Very safe", "B. Not safe", "C. Depends on phone brand", "D. Safe if phone is not lost"], "correct_answer_index": 1, "explanation": "Sensitive data must always be protected by encryption or a lock."},
        {"question": "A safe browser usually...", "options": ["A. Warns about dangerous sites", "B. Is colored blue", "C. Is the fastest", "D. Cannot open YouTube"], "correct_answer_index": 0, "explanation": "Modern browsers have phishing site databases updated every hour."},
        {"question": "Updating apps regularly is useful for...", "options": ["A. Using up data", "B. Only adding new features", "C. Closing security holes (Patching)", "D. Changing appearance"], "correct_answer_index": 2, "explanation": "Many hacks happen because old app versions have security flaws."},
        {"question": "If someone calls claiming to be the bank asking for card data, what is your action?", "options": ["A. Just give it", "B. Reject and call back the bank's official number", "C. Get angry", "D. Turn off phone"], "correct_answer_index": 1, "explanation": "Official banks never ask for card data through incoming calls."},
        {"question": "Official company emails usually use the domain...", "options": ["A. @gmail.com", "B. @yahoo.com", "C. @company-name.com", "D. @company-promo.tk"], "correct_answer_index": 2, "explanation": "Large companies always have their own email domains."},
        {"question": "What is the use of the 'Report Spam' feature in email?", "options": ["A. To fill up email", "B. To train email filters to be smarter", "C. To delete our account", "D. To send back a virus"], "correct_answer_index": 1, "explanation": "Your report helps protect other users from the same scammer."}
    ],
    3: [ # Social Engineering
        {"question": "What is the main weapon of Social Engineering?", "options": ["A. Advanced computers", "B. Emotional manipulation (fear, joy, urgency)", "C. Firearms", "D. Internet cables"], "correct_answer_index": 1, "explanation": "Scammers target human psychological vulnerabilities."},
        {"question": "What is 'Pretexting'?", "options": ["A. Free SMS", "B. Creating a fake scenario to gain trust", "C. Deleting text", "D. Adding followers"], "correct_answer_index": 1, "explanation": "Scammers pretend to be couriers, police, or bank staff."},
        {"question": "The 'Baiting' technique usually uses...", "options": ["A. Attractive bait (gifts/giveaways)", "B. Threat of imprisonment", "C. Broken links", "D. Condolences"], "correct_answer_index": 0, "explanation": "Victims are lured by promises of free gifts or benefits."},
        {"question": "Why is Social Engineering so dangerous?", "options": ["A. Difficult for antivirus to detect", "B. Can damage your phone", "C. Only for old people", "D. Drains battery"], "correct_answer_index": 0, "explanation": "Advanced technology is useless if humans willingly hand over data."},
        {"question": "What is 'Quid Pro Quo' in scams?", "options": ["A. Asking for something in return for fake help", "B. Winning a lottery", "C. Buying goods", "D. Selling data"], "correct_answer_index": 0, "explanation": "Scammers offer 'technical support' but ask for passwords as a condition."},
        {"question": "How to handle a scammer acting panicked/urgent?", "options": ["A. Panic too", "B. Stay calm and verify the information", "C. Transfer immediately", "D. Turn off lights"], "correct_answer_index": 1, "explanation": "Calmness is key to seeing the lies in the scammer's story."},
        {"question": "What information are scammers most looking for on social media?", "options": ["A. Food photos", "B. Personal data (mother's name, birthdate, location)", "C. Funny videos", "D. Sports news"], "correct_answer_index": 1, "explanation": "Personal data is used to answer your account security questions."},
        {"question": "What is 'Shoulder Surfing'?", "options": ["A. Surfing at the beach", "B. Peeking at a password over someone's shoulder", "C. Fixing a shoulder", "D. Stealing clothes"], "correct_answer_index": 1, "explanation": "A simple yet effective physical form of social engineering."},
        {"question": "If a stranger acts overly friendly and asks for office secrets, it is called...", "options": ["A. Being polite", "B. Elicitation (information gathering)", "C. Interview", "D. Venting"], "correct_answer_index": 1, "explanation": "Building trust is the initial stage of Social Engineering."},
        {"question": "The best defense against Social Engineering?", "options": ["A. Stop socializing", "B. Skeptical attitude and always verifying", "C. Change phone every month", "D. Wear sunglasses"], "correct_answer_index": 1, "explanation": "Don't trust easily; always verify the truth of the information."}
    ],
    4: [ # Spear Phishing & Whaling
        {"question": "What is the difference between regular Phishing and Spear Phishing?", "options": ["A. Phishing is faster", "B. Spear phishing targets specific individuals", "C. Phishing is only via SMS", "D. No difference"], "correct_answer_index": 1, "explanation": "Spear phishing uses your personal information to look very convincing."},
        {"question": "What is 'Whaling'?", "options": ["A. Hunting whales", "B. Phishing targeting big bosses/executives", "C. Catching fish", "D. Mass attack"], "correct_answer_index": 1, "explanation": "Whaling targets 'big fish' because they have access to big money/data."},
        {"question": "Who is usually the target of Whaling?", "options": ["A. Students", "B. Chief Financial Officer (CFO)", "C. Social media admin", "D. School children"], "correct_answer_index": 1, "explanation": "Company executives are prime targets due to their authority."},
        {"question": "Why is Spear Phishing hard to recognize?", "options": ["A. Uses foreign languages", "B. Uses details known to very few people", "C. Links are short", "D. Sent at midnight"], "correct_answer_index": 1, "explanation": "Scammers conduct deep research on targets before attacking."},
        {"question": "What is 'Business Email Compromise' (BEC)?", "options": ["A. Business email crash", "B. Hijacking office email to request money transfers", "C. Creating new email", "D. Selling products via email"], "correct_answer_index": 1, "explanation": "A variation of spear phishing causing billions in corporate losses."},
        {"question": "How to tell a real boss's email from a fake one?", "options": ["A. Check the send time", "B. Verify through another channel (phone/in-person)", "C. Check text length", "D. Ensure no typos"], "correct_answer_index": 1, "explanation": "Never trust just one communication channel (email)."},
        {"question": "What is the risk of Whaling for a company?", "options": ["A. Broken computers", "B. Massive financial loss and data breach", "C. Internet quota runs out", "D. Employees become lazy"], "correct_answer_index": 1, "explanation": "One successful attack on a boss can destroy a company's reputation."},
        {"question": "Scammers' information sources for Spear Phishing?", "options": ["A. LinkedIn, Company Website, Social Media", "B. Textbooks", "C. Bookstores", "D. Library"], "correct_answer_index": 0, "explanation": "Your public data is the scammer's capital to design attacks."},
        {"question": "Which best indicates Spear Phishing?", "options": ["A. 'Hello customer...'", "B. 'Hello Budi, how is the March tax report?'", "C. 'Lottery winner...'", "D. 'Account blocked...'"], "correct_answer_index": 1, "explanation": "Using specific names and details is its hallmark."},
        {"question": "Can regular employees fall victim to Spear Phishing?", "options": ["A. Impossible", "B. Yes, if they have access to important data", "C. Only if they are wrong", "D. If ordered by the boss"], "correct_answer_index": 1, "explanation": "Anyone with a 'key' to the company can be a target."}
    ],
    5: [ # Advanced Threats - Malware & Zero-Day
        {"question": "What is Malware?", "options": ["A. Expensive software", "B. Malicious software (viruses, worms, trojans)", "C. Hardware", "D. Design software"], "correct_answer_index": 1, "explanation": "Malware stands for Malicious Software."},
        {"question": "What is a 'Zero-Day Vulnerability'?", "options": ["A. Flaw unknown to the software creator", "B. Virus that lives 0 days", "C. Free app", "D. Auto-update"], "correct_answer_index": 0, "explanation": "Very dangerous because there is no 'cure' (patch) yet."},
        {"question": "How do Trojans infect computers?", "options": ["A. Disguise as useful programs", "B. Jump through cables", "C. Through the air", "D. Through the casing"], "correct_answer_index": 0, "explanation": "Like the Trojan horse, looks good outside but malicious inside."},
        {"question": "What is the function of 'Ransomware'?", "options": ["A. Steals phone credit", "B. Locks data and demands a ransom", "C. Speeds up PC", "D. Deletes history"], "correct_answer_index": 1, "explanation": "Ransomware holds your data hostage for money."},
        {"question": "Spyware is used to...", "options": ["A. Secretly spy on user activity", "B. Play games", "C. Send large files", "D. Edit videos"], "correct_answer_index": 0, "explanation": "Spyware records keyboard strokes (keyloggers) to your camera."},
        {"question": "Most common way malware enters phones?", "options": ["A. Via phone call", "B. Downloading apps outside Play Store/App Store", "C. Sunlight", "D. Via casing"], "correct_answer_index": 1, "explanation": "Modded or free apps on dark sites are often laced with malware."},
        {"question": "What is a 'Botnet'?", "options": ["A. Internet robot", "B. Network of infected computers controlled by criminals", "C. Smart chatbot", "D. Game server"], "correct_answer_index": 1, "explanation": "Your computer can become a 'zombie' to attack others."},
        {"question": "Adware is...", "options": ["A. Annoying advertising software", "B. TV ads", "C. Selling goods", "D. Digital billboards"], "correct_answer_index": 0, "explanation": "While less dangerous than viruses, it severely compromises privacy."},
        {"question": "What is a sign of malware infection?", "options": ["A. Monitor gets cleaner", "B. Slow performance and weird pop-ups", "C. Free internet", "D. Fan noise stops"], "correct_answer_index": 1, "explanation": "Background malware activity drains system resources."},
        {"question": "Why use an Antivirus?", "options": ["A. To make PC heavy", "B. Detects and removes malware threats", "C. To play games", "D. Office orders"], "correct_answer_index": 1, "explanation": "Antivirus is the digital security guard for your data."}
    ],
    6: [ # Ransomware Basics
        {"question": "The main goal of Ransomware creators is...", "options": ["A. Fame", "B. Financial Gain", "C. Helping people", "D. Destroying the internet"], "correct_answer_index": 1, "explanation": "The main motivation is extorting victims for material gain."},
        {"question": "Should we pay the Ransomware ransom?", "options": ["A. Yes, data will definitely return", "B. Not recommended, as data return is not guaranteed", "C. Depends on the price", "D. Just pay half"], "correct_answer_index": 1, "explanation": "Paying funds criminals and doesn't guarantee the decryption key."},
        {"question": "Best defense against Ransomware?", "options": ["A. Just Antivirus", "B. Regular data backups in a separate (Offline) location", "C. Use a new laptop", "D. Don't save data"], "correct_answer_index": 1, "explanation": "If you have backups, just wipe the system and restore without paying."},
        {"question": "How does Ransomware spread in an office?", "options": ["A. Via AC", "B. Via network (Lateral movement)", "C. Via windows", "D. Via phone"], "correct_answer_index": 1, "explanation": "If one person gets infected, the whole office server can be locked."},
        {"question": "What is 'Encryption' in Ransomware?", "options": ["A. Deleting data", "B. Scrambling data so it cannot be read without a key", "C. Copying data", "D. Selling data"], "correct_answer_index": 1, "explanation": "Data remains, but its contents cannot be opened at all."},
        {"question": "Sign of a Ransomware infection?", "options": ["A. File names change and cannot be opened", "B. Files get smaller", "C. Files disappear", "D. Folder colors turn red"], "correct_answer_index": 0, "explanation": "Usually file extensions change (e.g., .crypt or .locked)."},
        {"question": "What is a 'Ransom Note'?", "options": ["A. Love letter", "B. Message from criminals with payment instructions", "C. Shopping receipt", "D. Guidebook"], "correct_answer_index": 1, "explanation": "This message usually appears on the wallpaper or text files in every folder."},
        {"question": "The payment method demanded by criminals is usually...", "options": ["A. Bank transfer", "B. Phone credit", "C. Cryptocurrency (Bitcoin/Monero)", "D. Cash"], "correct_answer_index": 2, "explanation": "Crypto is hard for authorities to trace."},
        {"question": "WannaCry is an example of...", "options": ["A. Game", "B. A famous global ransomware", "C. Artist name", "D. Diet app"], "correct_answer_index": 1, "explanation": "Attacked hundreds of thousands of computers worldwide in 2017."},
        {"question": "When is the best time to backup?", "options": ["A. When infected by a virus", "B. Regularly (Daily/Weekly)", "C. Once a year", "D. Right before buying a new laptop"], "correct_answer_index": 1, "explanation": "Consistency is the key to data safety."}
    ],
    7: [ # Incident Response
        {"question": "First step when realizing an attack occurred?", "options": ["A. Panic", "B. Identification (Confirm what happened)", "C. Run", "D. Get angry"], "correct_answer_index": 1, "explanation": "Knowing the attack type helps determine the next steps."},
        {"question": "What is meant by 'Containment'?", "options": ["A. Deleting data", "B. Isolating infected parts so it doesn't spread", "C. Buying new servers", "D. Reporting to police"], "correct_answer_index": 1, "explanation": "Just like quarantine when sick, so it doesn't infect other computers."},
        {"question": "Who should be contacted first in the office?", "options": ["A. Office boy", "B. IT / Information Security Team", "C. Seatmate", "D. Family"], "correct_answer_index": 1, "explanation": "Professional teams have specific procedures for handling incidents."},
        {"question": "What is 'Eradication'?", "options": ["A. Eliminating the root cause of the attack", "B. Adding more viruses", "C. Changing office name", "D. Reinstalling Windows without checking"], "correct_answer_index": 0, "explanation": "Ensuring no loopholes remain for attackers to use again."},
        {"question": "Why are system logs very important?", "options": ["A. Uses up memory", "B. Activity trail record for investigation", "C. Just decoration", "D. Windows command"], "correct_answer_index": 1, "explanation": "Logs are silent witnesses to everything the intruder did."},
        {"question": "What is 'Post-Incident Activity'?", "options": ["A. Vacation", "B. Evaluation and learning so it doesn't happen again", "C. Disbanding the team", "D. Deleting all data"], "correct_answer_index": 1, "explanation": "Learning from mistakes is the most important part of security."},
        {"question": "Is it okay to turn off the computer (Power Off) during an attack?", "options": ["A. Yes, always", "B. Depends on instructions (RAM evidence might be lost)", "C. Not at all", "D. Just unplug it"], "correct_answer_index": 1, "explanation": "Force shutting down can delete digital traces in temporary memory."},
        {"question": "What is the use of backups in Incident Response?", "options": ["A. Increases costs", "B. Speeds up the recovery process", "C. Makes servers heavy", "D. Useless"], "correct_answer_index": 1, "explanation": "Data recovery is the final stage to return business to normal."},
        {"question": "If customer data leaks, what is the company's obligation?", "options": ["A. Stay silent", "B. Inform the public and authorities", "C. Pretend not to know", "D. Delete website"], "correct_answer_index": 1, "explanation": "Transparency is important to protect victim rights."},
        {"question": "Communication during an incident must...", "options": ["A. Be through one official channel", "B. Via gossip", "C. Free for anyone", "D. No need to talk"], "correct_answer_index": 0, "explanation": "Conflicting information will only add to the panic."}
    ],
    8: [ # Advanced Detection & CTI
        {"question": "What does CTI stand for?", "options": ["A. Cyber Teknik Indonesia", "B. Cyber Threat Intelligence", "C. Computer Tool International", "D. Cyber Team Investigation"], "correct_answer_index": 1, "explanation": "CTI is the process of gathering information about cyber threats."},
        {"question": "What is the use of CTI for a company?", "options": ["A. Knowing who might attack", "B. Finding new employees", "C. Calculating salary", "D. Fixing printers"], "correct_answer_index": 0, "explanation": "Knowing the enemy helps us prepare the right defense."},
        {"question": "What are 'Indicators of Compromise' (IoC)?", "options": ["A. Gas indicator", "B. Digital signs that a system has been breached", "C. Speed indicator", "D. Monitor light"], "correct_answer_index": 1, "explanation": "Examples include criminal IP addresses, virus file hashes, or fake domains."},
        {"question": "An Advanced Persistent Threat (APT) is...", "options": ["A. Fast virus", "B. Sophisticated, long-term planned attack", "C. Chat app", "D. Hardware"], "correct_answer_index": 1, "explanation": "Usually carried out by organized groups or state-sponsored actors."},
        {"question": "What is 'Threat Hunting'?", "options": ["A. Hunting viruses in the forest", "B. Proactively searching for threats before alarms sound", "C. Playing shooting games", "D. Buying new antivirus"], "correct_answer_index": 1, "explanation": "Not waiting to be attacked, but looking for intruders who might be hiding."},
        {"question": "Deep Web vs Dark Web, which is more dangerous?", "options": ["A. Deep Web", "B. Dark Web (Often used for illegal activities)", "C. Same", "D. Neither are dangerous"], "correct_answer_index": 1, "explanation": "Dark web needs special software and has many black markets for leaked data."},
        {"question": "What is 'Zero-Trust'?", "options": ["A. Trusting no one on the network", "B. Having no friends", "C. Selling accounts", "D. System without passwords"], "correct_answer_index": 0, "explanation": "The security philosophy of 'Never Trust, Always Verify'."},
        {"question": "CTI analysts often monitor underground forums to...", "options": ["A. Buy and sell goods", "B. See if company data is being sold", "C. Find entertainment", "D. Learn to cook"], "correct_answer_index": 1, "explanation": "Discovering leaks early can save the company."},
        {"question": "What is a 'Sandbox' in security?", "options": ["A. Toy sandbox", "B. Isolated environment for testing malicious files", "C. Data storage place", "D. Antivirus name"], "correct_answer_index": 1, "explanation": "Files are tested in a safe 'box'; if they explode, they don't harm the main system."},
        {"question": "Ideal cybersecurity is...", "options": ["A. Reactive (after the fact)", "B. Proactive (preventing before it happens)", "C. Passive (doing nothing)", "D. Secret"], "correct_answer_index": 1, "explanation": "Prevention is always cheaper and safer than curing."}
    ]
}
